# Generated by Django 4.2 on 2023-05-09 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.IntegerField(null=True)),
                ('date_start', models.DateField()),
                ('spaces_remaining', models.IntegerField()),
                ('type_program', models.CharField(choices=[('new_driver_full_program', 'New driver full program'), ('hour_lesson', 'Lessons by the hour'), ('road_test_preparation', 'Road test preparation'), ('refresher_driver_training', 'Refresher driver training')])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
