# Generated by Django 4.2 on 2023-05-09 15:59
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='spaces_remaining',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='type_program',
            field=models.CharField(
                choices=[('new_driver_full_program', 'New driver full program'), ('hour_lesson', 'Lessons by the hour'),
                         ('road_test_preparation', 'Road test preparation'),
                         ('refresher_driver_training', 'Refresher driver training')], null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=200)),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='courses',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
        )

    ]
