# Generated by Django 4.2 on 2023-05-09 15:59
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0003_courses_cost_courses_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=200)),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='courses',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
        ),
    ]
