# Generated by Django 4.2 on 2023-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_courses_cost_remove_courses_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='spaces_remaining',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='type_program',
            field=models.CharField(choices=[('new_driver_full_program', 'New driver full program'), ('hour_lesson', 'Lessons by the hour'), ('road_test_preparation', 'Road test preparation'), ('refresher_driver_training', 'Refresher driver training')], null=True),
        ),
    ]
