# Generated by Django 4.2 on 2023-05-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courses_cost_courses_date_start_courses_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='name',
        ),
        migrations.AddField(
            model_name='courses',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(choices=[('sat_class', 'Saturday Class'), ('day_class', 'Day Class'), ('evening_class', 'Evening Class'), ('sat_sun_class', 'Sat. & San. Class'), ('christmas_break_class', 'Christmas Break Class')], null=True),
        ),
    ]
